function AG1_groupModelSpec(subpar)
% function par_mod_spec(subpar)
% Set up the design matrix and run a design.
% 
% subpar refers to either the subject number (in string notation) or
% the par struct generated by par = par_params(subject)
% 
% jbh 7/24/08
%subjArray = sort({'ag1_021509'  'ag1_061109'  'ag1_062309' 'ag1_071309'  'ag1_071509' 'ag1_021809'  'ag1_040809'  'ag1_061309'  'ag1_062809'  'ag1_071409'  'ag1_080509'});  
%subjArray = sort({'ag1_021509'  'ag1_061109'  'ag1_062309' 'ag1_071309'  'ag1_071509' 'ag1_040809'  'ag1_061309'  'ag1_062809'  'ag1_071409'  'ag1_080509'});  

%tasks = {'enc' 'ret' 'respSel' 'loc'};


origdir = pwd;


if isstruct(subpar) % if it is par_params struct
    par = subpar;
else % assume subject string
    par = PM_GroupParams(subpar);
end
%specialNameVar(1).name = 'CorByGreaterEvidence_guessCor_vsFix';
%pecialNameVar(2).name = 'CorByLessEvidence_guessCor_vsFix';

for t = 1:length(par.tasks)
    clear jobs
    load (par.modelTemplate)   %%/Users/alangordon/Accumulator_fMRI/AG1/scripts/GroupTemplate.mat;
    
    
    
    yTemplate = load(par.task{t}.conTemplate);
    yCons = yTemplate.SPM.xCon;
    
    for c= 1:length(yCons);
        
        jobs{c}.stats{1}.factorial_design.des.t1.scans = [];
        
%         if ~exist(fullfile(expt_dir, 'group_analyses', tasks{t}, yCons(c).name));
%             mkdir(fullfile(expt_dir, 'group_analyses', tasks{t}, yCons(c).name));
%         end

         
         if ~exist(fullfile(par.expt_dir, 'group_analyses', par.tasks{t}, par.task{t}.SPMcons(c).name));
             mkdir(fullfile(par.expt_dir, 'group_analyses', par.tasks{t}, par.task{t}.SPMcons(c).name));
         end
        
        %jobs{c}.stats{1}.factorial_design.dir = {fullfile(expt_dir, 'group_analyses', tasks{t}, yCons(c).name)};
        jobs{c}.stats{1}.factorial_design.dir = {fullfile(par.expt_dir, 'group_analyses', par.tasks{t}, par.task{t}.SPMcons(c).name)};
        
        jobs{c}.stats{1}.factorial_design.masking.em{1} = par.exMask;
        
        if ~isempty(par.covVec)
          jobs{c}.stats{1}.factorial_design.cov(1).cname = par.covName; 
          jobs{c}.stats{1}.factorial_design.cov(1).c = par.covVec;
          jobs{c}.stats{1}.factorial_design.cov(1).iCC = 1;
          jobs{c}.stats{1}.factorial_design.cov(1).iCFI = 1;
        end
        
        for s = 1:length(par.subjArray)
            
%             if c<10
%                 cStr = ['0' num2str(c)];
%             else
%                 cStr = num2str(c);
%             end
%             
            
            jobs{c}.stats{1}.factorial_design.des.t1.scans{s} = fullfile(par.expt_dir, par.subjArray{s}, par.conGroup{t}, ['con_' prepend(num2str(c), 4) '.img']);
            
        end
        
        
    end

spm_jobman('run',jobs)
    
end


        
        
        
        
        
        
        
        
