function par_normfuncs(subpar)
% function par_normfuncs(subpar)
% normalize functionals
% 
% subpar refers to either the subject number (in string notation) or 
% the par struct generated by par = par_params(subject)
% 
% jbh 7/23/08

origdir = pwd;

% ---load par params if need be---

if isstruct(subpar) % if it is par_params struct
    par = subpar;
else % assume subject string
    par = par_params(subpar);
end


fprintf('---Normalizing funcs for Subject %d---\n',par.subNo);

graywrimg = par.graywrimg;
grwrflags = par.grwrflags;
[grpth,grnm] = fileparts(graywrimg);
grmatname        = fullfile(grpth,[grnm '_sn.mat']);
spm_write_sn(vertcat(par.ascanfiles{:}), grmatname,grwrflags);

fprintf('---Normalizing funcs COMPLETED for Subject %d---\n',par.subNo);


cd(origdir);