function PM_smoothfuncs(subpar)
% function par_smoothfuncs(subpar)
% smoooooooooove, baby
% 
% subpar refers to either the subject number (in string notation) or 
% the par struct generated by par = par_params(subject)
% 
% jbh 7/23/08

origdir = pwd;

% ---load par params if need be---

if isstruct(subpar) % if it is par_params struct
    par = subpar;
else % assume subject string
    par = par_params(subpar);
end



fprintf('---Smoothing for %s---\n',par.substr);


Sn     = size(par.wascanfiles,1);
% forloop taken from spm_config_smooth (spm didn't like my original way of
% doing it)
for i = 1:Sn
    Q = deblank(par.wascanfiles(i,:));
    [pth,nam,xt,nm] = spm_fileparts(deblank(Q));
    U = fullfile(pth,['s' nam xt nm]);
    spm_smooth(Q,U,par.s6mm_smoothkernel);
end

fprintf('---Smoothing COMPLETED for %s---\n',par.substr);

cd(origdir);